### ISSUE TITLE
Mulle-Objc Contributor Communication

### ISSUE THREAD

**Issue by Maximus-** [mulle-objc/mulle-objc.github.io#5]
There should be a  better way to discuss major decisions, future goals, timelines, et al. between core contributors. I've already mentioned the IRC channel on Freenode, but of course, there's only two people in the channel including myself. 

Slack has been mentioned, however, it's not public, and doesn't really follow the opensource philosophy. Taking suggestions as well for where we could host discussion and development.

**Comment by mulle-nat** [comment]
Yeah, good question. So what are the options ?

* mailing list  
* reddit board (?)
* IRC
* Slack
* Some opensource Slack like Rocket or Mattermost or so

What else ?

**Comment by mulle-nat** [comment]
In general for bug reports and questions I still prefer GH issues, because that's just more managable. The new communication channel should be chatty to distinguish it from GH issues.

Here's my view on the +/- on each:

* mailing list: asynchronous, history, somewhat linkable, inconvenient for chatting, easy to maintain
* reddit board:  asynchronous, history,  linkable, not that great for chatting IMO, easy to maintain
* IRC: synchronous, no history, not linkable, great for chatting, easy to maintain
* Slack: asynchronous, limited history,  linkable, pretty nice for chatting, easy to maintain 
* Rocket: like Slack I assume, hard to maintain 

My preference would be something like Slack. It would be open to members, that gives a tangible benefit to become a member :) Topics of interest could be copy/pasted into the Wiki.

**Comment by clozinski** [comment]
> Topics of interest could be copy/pasted into the Wiki.
That never happens.  I have been watching the ZODB mailing list for years.  Traffic is getting heavy, so I do not read all the emails.  Great stuff in there, but it is impossible to find it.  

Conversations  need to be organized as  a hierarchy.  Then there is a historical record of each  subject.  The process of discussion generates the documentation.  

My advice would be to use
http://blogory.org/mulle-objc
to discuss mulle-objc. 

Blogory is a proper content management system.  Blogory is organized as a tree of subjects.   You can add multiple content types to the appropriate subject category.  You can subscribe to the RSS feed for any branch that interests you. The process of discussing mulle-objc will build a hierarchical tree of knowledge about the product.  The discussion process effectively writes the documentation.   It is easy to find what you want.   It is easy  go  back and clean up any branch, turning it into the documentation.  
  
Warm Regrds
Chris

**Comment by mulle-nat** [comment]
I don't know, if I look at Blogory it looks to me like a more structured Wiki. But what we are looking for is some sort of improved chat platform, where you don't really put _that_ much thought into it. It's also nice to have some kind of integrations with github and travis-ci, so that commits are automatically mirrored. 

I wouldn't just send an email or make a blogory posting to just say "hi" or so, but I would do that in IRC/Slack.

**Comment by mulle-nat** [comment]
If you are a public member and you don't get an invite, that means that I can't get your email address from github. Just let me know your email address and I will send you an invite.
